#@BaseApiUrl = http://localhost:5001/api
@BaseApiUrl = https://localhost:7001/api

@BearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOTk4NjE4Ni0zOTkxLTRkNTYtOWE0MC1iOTMzZjVhZTJjMDIiLCJ1bmlxdWVfbmFtZSI6InphbmVAZXhhbXBsZS5jb20iLCJlbWFpbCI6InphbmVAZXhhbXBsZS5jb20iLCJleHAiOjE3Mzk1MjM1OTAsImlzcyI6InphbmVzdGFja2VkIn0.73aZrJBie1XvX0j4zO45SW9lMfidFTYWER9C6vf1Spg

### Register a New User
POST {{BaseApiUrl}}/auth/register
Content-Type: application/json

{
  "username": "user",
  "email": "user@example.com",
  "password": "Password1*"
}


### Login and Get JWT Token
# Copy the token from the response and replace BearerToken with the new token
POST {{BaseApiUrl}}/auth/login-jwt
Content-Type: application/json

{
  "username": "user@example.com",
  "password": "Password1*"
}


### Get All Skills (Public)
GET {{BaseApiUrl}}/skills
Accept: application/json


### Get All Projects (Public)
GET {{BaseApiUrl}}/projects
Accept: application/json


### Create a Skill (Unauthorized - Should Fail)
POST {{BaseApiUrl}}/skills
Content-Type: application/json

{
  "name": "GraphQL",
  "yearsOfExperience": 1,
  "proficiency": "Intermediate"
}


### Create a Skill (Authorized - Should Succeed)
POST {{BaseApiUrl}}/skills
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

{
  "name": "GraphQL",
  "yearsOfExperience": 1,
  "proficiency": "Intermediate"
}


### Get Skill By ID (Public)
GET {{BaseApiUrl}}/skills/1
Accept: application/json


### Update Skill (Unauthorized - Should Fail)
PUT {{BaseApiUrl}}/skills/1
Content-Type: application/json

{
  "id": 1,
  "name": "GraphQL",
  "yearsOfExperience": 2,
  "proficiency": "Advanced"
}


### Update Skill (Authorized - Should Succeed)
PUT {{BaseApiUrl}}/skills/1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

{
  "id": 1,
  "name": "GraphQL",
  "yearsOfExperience": 2,
  "proficiency": "Advanced"
}


### Delete Skill (Unauthorized - Should Fail)
DELETE {{BaseApiUrl}}/skills/1


### Delete Skill (Authorized - Should Succeed)
DELETE {{BaseApiUrl}}/skills/9
Authorization: Bearer {{BearerToken}}